# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import msg_pb2 as msg__pb2


class KleeHelperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.kleeGenerate = channel.unary_unary(
                '/msg.KleeHelper/kleeGenerate',
                request_serializer=msg__pb2.FilePath.SerializeToString,
                response_deserializer=msg__pb2.TestCaseNumber.FromString,
                )
        self.kleeShowTestCase = channel.unary_unary(
                '/msg.KleeHelper/kleeShowTestCase',
                request_serializer=msg__pb2.TestCaseName.SerializeToString,
                response_deserializer=msg__pb2.TestCaseContent.FromString,
                )


class KleeHelperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def kleeGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def kleeShowTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KleeHelperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'kleeGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.kleeGenerate,
                    request_deserializer=msg__pb2.FilePath.FromString,
                    response_serializer=msg__pb2.TestCaseNumber.SerializeToString,
            ),
            'kleeShowTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.kleeShowTestCase,
                    request_deserializer=msg__pb2.TestCaseName.FromString,
                    response_serializer=msg__pb2.TestCaseContent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msg.KleeHelper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KleeHelper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def kleeGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msg.KleeHelper/kleeGenerate',
            msg__pb2.FilePath.SerializeToString,
            msg__pb2.TestCaseNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def kleeShowTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msg.KleeHelper/kleeShowTestCase',
            msg__pb2.TestCaseName.SerializeToString,
            msg__pb2.TestCaseContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
