# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x03msg\"\x18\n\x08\x46ilePath\x12\x0c\n\x04path\x18\x01 \x01(\t\" \n\x0eTestCaseNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1c\n\x0cTestCaseName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fTestCaseContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2\x81\x01\n\nKleeHelper\x12\x34\n\x0ckleeGenerate\x12\r.msg.FilePath\x1a\x13.msg.TestCaseNumber\"\x00\x12=\n\x10kleeShowTestCase\x12\x11.msg.TestCaseName\x1a\x14.msg.TestCaseContent\"\x00\x62\x06proto3')



_FILEPATH = DESCRIPTOR.message_types_by_name['FilePath']
_TESTCASENUMBER = DESCRIPTOR.message_types_by_name['TestCaseNumber']
_TESTCASENAME = DESCRIPTOR.message_types_by_name['TestCaseName']
_TESTCASECONTENT = DESCRIPTOR.message_types_by_name['TestCaseContent']
FilePath = _reflection.GeneratedProtocolMessageType('FilePath', (_message.Message,), {
  'DESCRIPTOR' : _FILEPATH,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.FilePath)
  })
_sym_db.RegisterMessage(FilePath)

TestCaseNumber = _reflection.GeneratedProtocolMessageType('TestCaseNumber', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASENUMBER,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.TestCaseNumber)
  })
_sym_db.RegisterMessage(TestCaseNumber)

TestCaseName = _reflection.GeneratedProtocolMessageType('TestCaseName', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASENAME,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.TestCaseName)
  })
_sym_db.RegisterMessage(TestCaseName)

TestCaseContent = _reflection.GeneratedProtocolMessageType('TestCaseContent', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASECONTENT,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.TestCaseContent)
  })
_sym_db.RegisterMessage(TestCaseContent)

_KLEEHELPER = DESCRIPTOR.services_by_name['KleeHelper']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEPATH._serialized_start=18
  _FILEPATH._serialized_end=42
  _TESTCASENUMBER._serialized_start=44
  _TESTCASENUMBER._serialized_end=76
  _TESTCASENAME._serialized_start=78
  _TESTCASENAME._serialized_end=106
  _TESTCASECONTENT._serialized_start=108
  _TESTCASECONTENT._serialized_end=142
  _KLEEHELPER._serialized_start=145
  _KLEEHELPER._serialized_end=274
# @@protoc_insertion_point(module_scope)
